### ISSUE TITLE
we use with branch with   \ / : * ? " > |

### ISSUE THREAD

**Issue by pakeng** [crowdin/android-studio-plugin#108]
**Describe the bug**

Branch name can't contain any of the following characters: \ / : * ? " > |

**To Reproduce**

In my project, we are using git with branch tree like :

 main :
  -- feature/bOne/1.0.0
  -- release/bOne/0.0.1

**Environment:**
1. Android Studio Flamingo | 2022.2.1 Patch 2
2. Ubuntu 23.04

In debug

2023-07-06 10:44:53.832 ERROR : java.lang.RuntimeException: Branch name can't contain any of the following characters: \ / : * ? " > | at com.crowdin.util.ActionUtils.getBranchName(ActionUtils.java:14) at com.crowdin.ui.action.RefreshTranslationProgressAction.performInBackground(RefreshTranslationProgressAction.java:79) at com.crowdin.action.BackgroundAction$1.run(BackgroundAction.java:31) at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442) at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683) at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jbushmaster007** [comment]
> **Describe the bug**
> 
> Branch name can't contain any of the following characters: \ / : * ? " > |
> 
> **To Reproduce**
> 
> In my project, we are using git with branch tree like :
> 
> main : -- feature/bOne/1.0.0 -- release/bOne/0.0.1
> 
> **Environment:**
> 
> 1. Android Studio Flamingo | 2022.2.1 Patch 2
> 2. Ubuntu 23.04
> 
> In debug
> 
> 2023-07-06 10:44:53.832 ERROR : java.lang.RuntimeException: Branch name can't contain any of the following characters: \ / : * ? " > | at com.crowdin.util.ActionUtils.getBranchName(ActionUtils.java:14) at com.crowdin.ui.action.RefreshTranslationProgressAction.performInBackground(RefreshTranslationProgressAction.java:79) at com.crowdin.action.BackgroundAction$1.run(BackgroundAction.java:31) at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442) at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683) at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by andrii-bodnar** [comment]
We had a similar issue in the native DVCS integrations.

The solution here is to:
- Replace all unsupported characters with a dot `.` before making the "Add Branch" API call. 
- The original branch name should be set as the branch [`title`](https://github.com/crowdin/crowdin-api-client-java/blob/master/src/main/java/com/crowdin/client/sourcefiles/model/AddBranchRequest.java#L10) value.
- Consider the branch title value if present, when resolving the branch ID during the translations download.

API reference: [api.projects.branches.post](https://developer.crowdin.com/api/v2/#operation/api.projects.branches.post)
